flowchart TD
    classDef person fill:#fffacd,stroke:#aaa,color:#333
    classDef org    fill:#cce5ff,stroke:#aaa,color:#333
    classDef service fill:#e6e6e6,stroke:#aaa,color:#333
    classDef lit    fill:none,stroke:none,font-style:italic,color:#2a7a2a
    classDef meta   fill:#f5f5ff,stroke:#9999cc,color:#333

    subgraph ctx["Graph"]
        direction LR
        ctx_meta["claimant: :Self\nsubject: :Facenook_Site\nshape: pshapes:ContactInfoShape"]:::meta
    end

    ndec3c20584d4[":Facenook_Site\n(WebsiteService)"]
    n1704f6b0182e("facenook.com"):::lit

    ndec3c20584d4 -->|"siteDomain"| n1704f6b0182e
